spring.application.name=notification

server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gugugaiteiro124@gmail.com
spring.mail.password=xjgq iexy siwc nlwb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true