#spring:
#  data:
#    mongodb:
#      auto-index-creation: true
#      host: localhost
#      port: 27017
#      database: orderdb
#      username: admin
#      password: 1234
server.port=8989
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=orderdb
spring.data.mongodb.username=admin
spring.data.mongodb.password=1234

stripe.secret=sk_test_51PUZrlKYsRfvT8LupcmQD2t0yJ9CmbU0yzgBkon4Q89zRBTvg54UWzRfBEkCk3kUqPdiD5N4LaVE7fYdt9DSTZwd00o9HSAg0T
