name: CI/CD Pipeline User-MS

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'user/**'
      - 'pom.xml'
  pull_request:
      branches: [ "develop" ]
      paths:
        - 'user/**'
        - 'pom.xml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - java-version: '17'
          - distribution: 'temurin'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: ${{matrix.distribution}}
          cache: maven


      - name: Build with maven
        run: mvn clean package -pl user -am -DskipTests=false
