name: CI/CD Pipeline User-MS

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'user/**'
      - 'pom.xml'
      - '.github/workflows/user-pipeline.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn clean package -pl user -am -DskipTests=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: user/target/*.jar

      - name: Upload Compose
        uses: actions/upload-artifact@v4
        with:
          name: user-service-compose
          path: user/docker-compose.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download Artifact
        uses: actions/download-artifact@v4
        with:
          name: user-service-jar
          path: deploy-artifacts

      - name: download compose
        uses: actions/download-artifact@v4
        with:
          name: user-service-compose
          path: deploy-compose

      - name: Show downloaded files
        run: |
          echo "Downloaded files:"
          ls -R

      - name: Create directory on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: mkdir -p /home/ec2-user/app-user

      - name: Prepare files to scp
        run: |
          mkdir -p final_package
          mv deploy-artifacts/*.jar final_package/
          mv deploy-compose/docker-compose.yaml final_package/
          echo "--- Conteúdo da pasta que será enviada ---"
          ls -l final_package/

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "final_package/*"

          target: "/home/ec2-user/app-user"
          strip_components: 1

      - name: Start App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app-user
            
            echo "--- Listando arquivos no diretorio ---"
            ls -la
            
            docker-compose down || true
            
            docker-compose up -d
            echo "Aguardando o banco subir"
            sleep 10
            
            sudo pkill -f 'java -jar' || true
            
            nohup java -jar *.jar \
            --spring.datasource.url=jdbc:postgresql://localhost:5431/postgres \
            --spring.datasource.username=postgres \
            --spring.datasource.password=1234 \
            > app.log 2>&1 &

            echo "Deploy finalizado com sucesso!"
